name: jmay
favicon: null
layout_spectrum: 0.42237
typography_spectrum: 0.37399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000c01'
    - '#beb8b8'
    - '#005615'
    - '#ecede8'
    - '#35a230'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
