name: jmay
favicon: null
layout_spectrum: 0.62201186735183
typography_spectrum: 0.021737309405580163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e363b'
    - '#fefaf9'
    - '#bcc0c8'
    - '#959daf'
    - '#826557'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.337986595928669
purpose: []
