name: jmay
favicon: null
layout_spectrum: 0.42237
typography_spectrum: 0.37399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e363b'
    - '#fefaf9'
    - '#bcc0c8'
    - '#959daf'
    - '#826557'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
